version: '3.4'  
  
services:  
    azure-blob-storage:  
        image: "mcr.microsoft.com/azure-blob-storage:latest"  
        hostname: azure-blob-storage  
        environment:  
            LOCAL_STORAGE_ACCOUNT_NAME: sample  
            LOCAL_STORAGE_ACCOUNT_KEY: "zRSmKbeUMb1NUkFjoGC9RA=="       
        volumes:
            - "blobdata:/blobroot"
        ports:
            - "11002:11002"
volumes:
  blobdata:
    